import { Worker, Job } from "bullmq";
import { PrismaClient } from "@prisma/client";
import { Pool } from "pg";
import { Resend } from "resend";
import dotenv from "dotenv";
import fs from "fs";
import path from "path";

// Load .env
const envPath = path.resolve(__dirname, "../../.env");
if (fs.existsSync(envPath)) {
    dotenv.config({ path: envPath });
} else {
    dotenv.config();
}

const prisma = new PrismaClient();
const resend = new Resend(process.env.RESEND_API_KEY || "re_dummy_key");

const connection = {
    host: process.env.REDIS_HOST || "localhost",
    port: parseInt(process.env.REDIS_PORT || "6379", 10),
    password: process.env.REDIS_PASSWORD || undefined,
};

console.log("Starting BullMQ Worker on reportQueue...");

const worker = new Worker(
    "reportQueue",
    async (job: Job) => {
        console.log(`Processing job ${job.id}:`, job.data);
        const { reportId } = job.data;

        if (!reportId) {
            throw new Error("Missing reportId in job data");
        }

        const report = await prisma.savedReport.findUnique({
            where: { id: reportId },
            include: { user: true },
        });

        if (!report || !report.user) {
            throw new Error(`Report ${reportId} not found or has no user`);
        }

        // We need the user's active DB connection. For a scheduled report, 
        // we'll default to their primary/first connection.
        const dbConns = await prisma.dbConnection.findMany({
            where: { userId: report.userId },
        });

        if (dbConns.length === 0) {
            throw new Error(`User ${report.userId} has no connected database`);
        }

        const activeConn = dbConns.find(c => c.isDefault) || dbConns[0];
        
        // Decrypt the connection string (we'll just use a mock decrypt or basic if not fully encrypted in this minimal setup, 
        // but since encrypt/decrypt uses crypto, we need the decrypt function. 
        // For simplicity, we'll assume the string can be used directly or we pull decrypt from lib)
        let connectionString = activeConn.dbConnectionString;
        try {
            // Note: in a real app, you would import the decrypt function from @/lib/crypto.
            // Assuming it's base64 encoded JSON for this demo, or plain text if not actually encrypted.
            if (connectionString.includes("iv")) {
                const crypto = require("crypto");
                const ENCRYPTION_KEY = process.env.ENCRYPTION_KEY || "default_encryption_key_32_chars_!!"; 
                const keyBuffer = crypto.scryptSync(ENCRYPTION_KEY, "salt", 32);
                
                const { iv, data, authTag } = JSON.parse(connectionString);
                const decipher = crypto.createDecipheriv("aes-256-gcm", keyBuffer, Buffer.from(iv, "hex"));
                decipher.setAuthTag(Buffer.from(authTag, "hex"));
                let decrypted = decipher.update(data, "hex", "utf8");
                decrypted += decipher.final("utf8");
                connectionString = decrypted;
            }
        } catch (err) {
            console.error("Decryption failed, assuming plain text", err);
        }

        console.log(`Executing SQL for report: ${report.title}`);

        let resultRows = [];
        try {
            // Basic PG pool execution
            const pool = new Pool({
                connectionString,
                ssl: { rejectUnauthorized: false },
                connectionTimeoutMillis: 10000,
            });

            const res = await pool.query(report.sql);
            resultRows = res.rows.slice(0, 50); // limit to 50 rows for the email
            await pool.end();
        } catch (dbErr: any) {
            throw new Error(`Database execution failed: ${dbErr.message}`);
        }

        // Format email
        const html = `
            <h2>${report.title}</h2>
            <p><strong>Prompt:</strong> ${report.prompt}</p>
            <h3>Results (Top 50 rows)</h3>
            <table border="1" cellpadding="5" cellspacing="0" style="border-collapse: collapse; font-family: monospace; font-size: 12px;">
                <thead>
                    <tr>
                        ${resultRows.length > 0 ? Object.keys(resultRows[0]).map(k => `<th>${k}</th>`).join("") : "<th>No Data</th>"}
                    </tr>
                </thead>
                <tbody>
                    ${resultRows.map((row: any) => `
                        <tr>
                            ${Object.values(row).map(v => `<td>${v}</td>`).join("")}
                        </tr>
                    `).join("")}
                </tbody>
            </table>
            <br />
            <p>Generated by Talk2DB Scheduled Reports.</p>
        `;

        console.log(`Sending email to ${report.user.email}...`);

        try {
            await resend.emails.send({
                from: "Talk2DB Reports <onboarding@resend.dev>", // using Resend's default test domain
                to: report.user.email,
                subject: `Scheduled Report: ${report.title}`,
                html,
            });
        } catch (emailErr: any) {
            console.error("Failed to send email", emailErr);
            throw new Error(`Email sending failed: ${emailErr.message}`);
        }

        // Update lastRunAt
        await prisma.savedReport.update({
            where: { id: reportId },
            data: { lastRunAt: new Date() },
        });

        console.log(`Job ${job.id} completed successfully.`);
        return { success: true, rowsCount: resultRows.length };
    },
    { connection }
);

worker.on("completed", (job) => {
    console.log(`Job ${job.id} completed!`);
});

worker.on("failed", (job, err) => {
    console.error(`Job ${job?.id} failed with error: ${err.message}`);
});
